#!/usr/bin/env bash

# git
source ${HOME}/scripts/git/git-prompt.sh
source ${HOME}/scripts/git/git-completion.bash
source ${HOME}/scripts/git/git.plugin.bash

# prompt 
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWUPSTREAM=auto
export PROMPT_COMMAND='__git_ps1 "\[\033[01;34m\]\u@\h \[\033[01;32m\]\w\[\033[01;31m\]" " \[\033[39m\]\$\[\033[0m\] "'

if [[ "$(command -v hub)" ]]; then
    alias git='hub';
fi

# Some git aliases
alias gs='git status';
alias gpul='git pull';
alias gf='git fetch';
alias grem='git remote';
alias gremv='git remote -v';
alias gpu='git push';
alias gpf='gpu -f'
alias gpfu='gpu -fu';
alias grev='git revert';
alias gcp='git cherry-pick';
alias gcpc='gcp --continue';
alias gcpa='gcp --abort';
alias gr='git reset';
alias grh='gr --hard';
alias grs='gr --soft';
alias grb='git rebase';
alias grbi='grb --interactive';
alias grbc='grb --continue';
alias grbs='grb --skip';
alias grba='grb --abort';
alias gb='git bisect';
alias gd='git diff';
alias gc='git commit';

# alias
alias inst="sudo pacman -S --noconfirm "
alias rem="sudo pacman -Rns "
alias update="sudo pacman -Syu --noconfirm "
alias ref="sudo reflector --latest 200 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist"
alias cu="checkupdates"

# Colors
BLINK_RED="\033[05;31m"
BLUE="\033[01;34m"
BOLD="\033[1m"
GRN="\033[01;32m"
RED="\033[01;31m"
RST="\033[0m"
YLW="\033[01;33m"

# Number of make threads
THREADS=$(nproc --all)
JOBS_FLAG="-j${THREADS}"

# Common ccache variable
CCACHE=$(command -v ccache)

# Directory
KERNELDIR="${HOME}/kernel";
LOS=${HOME}/android/lineage

if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# toolchain
CC_49=${HOME}/kernel/toolchain/aarch64-linux-gnu-4.x-linaro-20180409/bin/aarch64-linux-gnu-
CC_7=${HOME}/kernel/toolchain/aarch64-linux-gnu-7.x-linaro-20180411/bin/aarch64-linux-gnu-

# Use ccache
export USE_CCACHE=1;
if [[ -z "${CCACHE_DIR}" ]]; then
    export CCACHE_DIR="${HOME}/.ccache";
fi

function syncc() {
    time repo sync --force-broken --force-sync --detach --no-clone-bundle --current-branch --no-tags "$@";
}

function sjack() {
    . ${LOS}/prebuilts/sdk/tools/jack-admin stop-server
}

function los(){
	export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G"
	export PATH="/opt/python2:$PATH"
	export LC_ALL=C
	
	cd ${LOS}
	syncc
}
