#!/usr/bin/env bash

# Gather parameters
function parse_parameters() {
    while [[ ${#} -ge 1 ]]; do
        case ${1} in
            # Make cbz file
            "-cb"|"--mkacbz")
                for dir in */; do base=$(basename "$dir"); zip -r9 "${base}.cbz" "$dir"; done ;;

            # Convert zip to cbz
            "-mv"|"--mvcbz")
                for file in *.zip; do mv "$file" "${file%.zip}.cbz"; done ;;

            # Remove colon
            "-rc"|"--rmcolon")
                # shellcheck disable=SC2001
                for file in *.cbz; do mv "$file" "$(echo "$file" | sed 's/[^a-zA-Z0-9.[:space:]]//g')"; done ;;

            *)
                echo "Invalid parameter" ;;
        esac

        shift
    done

}

# Parse command line parameters
parse_parameters "${@}"
