#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2018 Dede Dindin Qudsy
#
# Update host from steven black repo https://github.com/StevenBlack/hosts

# Source common functions
source "$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" || return; pwd)/common"
trap 'echo; die "Manually aborted!"' SIGINT SIGTERM

# Existence sanity checks
cd "${HOME}/github/hosts" || die "Hosts folder doesn't exist, please clone!"

# Update the repo
header "Updating repos"
git fetch origin
git reset --hard origin/master

# Copy additional host
header "Copy Additional host, blacklist, and whitelist if exist"
[[ -f ${HOME}/github/myhosts ]] && cp -v ${HOME}/github/myhosts .
[[ -f ${HOME}/github/whitelist ]] && cp -v ${HOME}/github/whitelist .
[[ -f ${HOME}/github/blacklist ]] && cp -v ${HOME}/github/blacklist .

# Updating Host
header "Updating Host File"
python updateHostsFile.py --auto --replace --extensions fakenews gambling --flush-dns-cache
