#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2018-2019 Dede Dindin Qudsy
#
# Update host from steven black repo https://github.com/StevenBlack/hosts
#
# dependencies
# sudo pacman -S python-lxml python-beautifulsoup4 python-mock
# or
# pip3 install --user -r requirements.txt

# Source common functions
# shellcheck disable=SC1090
source "$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" || return; pwd)/common"
trap 'echo; die "Manually aborted!"' SIGINT SIGTERM

# Gather parameters on extension
while (( ${#} )); do
    case ${1} in
        # Extension
        "-e"|"--extension")
            shift && enforce_value "${@}"

            EX=$(sed 's/,/ /g' <<< "${1}") ;;
    esac
    shift
done

# Default parameters if no extension
[[ -z ${EX} ]] && EX="fakenews gambling"

# Existence sanity checks
cd "${HOME}/local/github/hosts" || die "Hosts folder doesn't exist, please clone!"

# Update the repo
header "Updating repos"
git fetch origin
git reset --hard origin/master

# Download bebasid hosts
header "Download bebasid hosts"
curl https://raw.githubusercontent.com/bebasid/bebasid/master/releases/hosts --output /tmp/hosts
mv /tmp/hosts myhosts

# Copy additional host
header "Copy Additional host, blacklist, and whitelist if exist"
[[ -f ${HOME}/local/github/myhosts ]] && cat -v ${HOME}/local/github/myhosts >> myhosts
[[ -f ${HOME}/local/github/whitelist ]] && cp -v "${HOME}/local/github/whitelist" .
[[ -f ${HOME}/local/github/blacklist ]] && cp -v "${HOME}/local/github/blacklist" .

# Updating Host
header "Updating Host File"
python updateHostsFile.py --auto --replace --extensions "${EX}" --flush-dns-cache
